"""

Revision ID: 76edce9c4d39
Revises: fadfc5730ced
Create Date: 2024-02-11 03:58:07.231875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76edce9c4d39'
down_revision: Union[str, None] = 'fadfc5730ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'is_favorite')
    # ### end Alembic commands ###
