"""

Revision ID: c167ca0e2e8b
Revises: 98d53a063eca
Create Date: 2024-02-11 04:27:30.651014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c167ca0e2e8b'
down_revision: Union[str, None] = '98d53a063eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark_prompt', sa.Column('prompt_message', sa.String(), nullable=False))
    op.drop_column('bookmark_prompt', 'promptid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark_prompt', sa.Column('promptid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bookmark_prompt', 'prompt_message')
    # ### end Alembic commands ###
